### ISSUE TITLE
AuthorNagException

### ISSUE THREAD

**Issue by wow4682** [Yamakaja/commanditems#1]
Appears when using Paper.

```
[11:58:25 WARN]: org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP
[11:58:25 WARN]: 	at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingType$1.newTiming(TimingType.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:72)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:38)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.<init>(BukkitCommandManager.java:87)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.PaperCommandManager.<init>(PaperCommandManager.java:33)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:35)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:58:25 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:58:25 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:58:25 WARN]: org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP
[11:58:25 WARN]: 	at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingType$1.newTiming(TimingType.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:72)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitRegisteredCommand.<init>(BukkitRegisteredCommand.java:35)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.createRegisteredCommand(BukkitCommandManager.java:330)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.registerSubcommand(BaseCommand.java:308)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.registerSubcommands(BaseCommand.java:217)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.onRegister(BaseCommand.java:145)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.onRegister(BaseCommand.java:124)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.registerCommand(BukkitCommandManager.java:184)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.registerCommand(BukkitCommandManager.java:217)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:50)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:58:25 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:58:25 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:58:25 WARN]: org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP
[11:58:25 WARN]: 	at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingType$1.newTiming(TimingType.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:72)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitRegisteredCommand.<init>(BukkitRegisteredCommand.java:35)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.createRegisteredCommand(BukkitCommandManager.java:330)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.registerSubcommand(BaseCommand.java:308)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.registerSubcommands(BaseCommand.java:254)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.onRegister(BaseCommand.java:145)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.onRegister(BaseCommand.java:124)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.registerCommand(BukkitCommandManager.java:184)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.registerCommand(BukkitCommandManager.java:217)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:50)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:58:25 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:58:25 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:58:25 WARN]: org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP
[11:58:25 WARN]: 	at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingType$1.newTiming(TimingType.java:11)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:72)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitRegisteredCommand.<init>(BukkitRegisteredCommand.java:35)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.createRegisteredCommand(BukkitCommandManager.java:330)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.registerSubcommand(BaseCommand.java:308)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.registerSubcommands(BaseCommand.java:254)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.onRegister(BaseCommand.java:145)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BaseCommand.onRegister(BaseCommand.java:124)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.registerCommand(BukkitCommandManager.java:184)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.registerCommand(BukkitCommandManager.java:217)
[11:58:25 WARN]: 	at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:50)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:58:25 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:58:25 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:58:25 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[11:58:25 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:58:25 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Yamakaja** [comment]
Mhm, looks like i need to update the version of aikar commands which is in use. I'll leave this open for now - expect an update in the next days

**Comment by paint2005** [comment]
same issue, am also on paper :/

**Comment by Yamakaja** [comment]
This code is part of [aikar/commands](https://github.com/aikar/commands) library, please open an issue there.
