### ISSUE TITLE
Can't enable 

### ISSUE THREAD

**Issue by Peskdt** [Yamakaja/commanditems#35]
It just happened I don't know why, teh plugin was working perfectly

14.04 09:53:06 [Server] INFO Enabling CommandItems v2.4.0
14.04 09:53:06 [Server] WARN Could not save config.yml to plugins/CommandItems/config.yml because config.yml already exists.
14.04 09:53:06 [Server] WARN Could not save messages.yml to plugins/CommandItems/messages.yml because messages.yml already exists.
14.04 09:53:07 [Server] ERROR Error occurred while enabling CommandItems v2.4.0 (Is it up to date?)
14.04 09:53:07 [Server] INFO java.lang.RuntimeException: Failed to read config!
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:39) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:37) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
14.04 09:53:07 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
14.04 09:53:07 [Server] INFO Caused by: me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.JsonMappingException: while parsing a block mapping
14.04 09:53:07 [Server] INFO in 'reader', line 10, column 3:
14.04 09:53:07 [Server] INFO fly:
14.04 09:53:07 [Server] INFO ^
14.04 09:53:07 [Server] INFO expected <block end>, but found BlockMappingStart
14.04 09:53:07 [Server] INFO in 'reader', line 123, column 4:
14.04 09:53:07 [Server] INFO transportador:
14.04 09:53:07 [Server] INFO ^
14.04 09:53:07 [Server] INFO at [Source: (File); line: 123, column: 4]
14.04 09:53:07 [Server] INFO at [Source: (File); line: 123, column: 4] (through reference chain: me.yamakaja.commanditems.data.CommandItemsConfig["items"])
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1689) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:289) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:37) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO ... 11 more
14.04 09:53:07 [Server] INFO Caused by: me.yamakaja.commanditems.lib.com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
14.04 09:53:07 [Server] INFO in 'reader', line 10, column 3:
14.04 09:53:07 [Server] INFO fly:
14.04 09:53:07 [Server] INFO ^
14.04 09:53:07 [Server] INFO expected <block end>, but found BlockMappingStart
14.04 09:53:07 [Server] INFO in 'reader', line 123, column 4:
14.04 09:53:07 [Server] INFO transportador:
14.04 09:53:07 [Server] INFO ^
14.04 09:53:07 [Server] INFO at [Source: (File); line: 123, column: 4]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:346) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:825) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:512) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:37) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO ... 11 more
14.04 09:53:07 [Server] INFO Caused by: me.yamakaja.commanditems.lib.org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
14.04 09:53:07 [Server] INFO in 'reader', line 10, column 3:
14.04 09:53:07 [Server] INFO fly:
14.04 09:53:07 [Server] INFO ^
14.04 09:53:07 [Server] INFO expected <block end>, but found BlockMappingStart
14.04 09:53:07 [Server] INFO in 'reader', line 123, column 4:
14.04 09:53:07 [Server] INFO transportador:
14.04 09:53:07 [Server] INFO ^
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:569) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:167) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:343) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:825) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:512) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:37) ~[CommandItems-2.4.0-all.jar:?]
14.04 09:53:07 [Server] INFO ... 11 more
14.04 09:53:07 [Server] INFO Disabling CommandItems v2.4.0

**Comment by Peskdt** [comment]
Fixed, it was a missconfig.

**Comment by Relaxing9** [comment]
> Fixed, it was a missconfig.

Lock issue?
