### ISSUE TITLE
Unable To Load Plugin

### ISSUE THREAD

**Issue by AdenGames** [Yamakaja/commanditems#4]
I'm on the latest version of spigot 1.8.8. 
Version 2.0.4 of the plugin and I have an issue where the plugin will not load even with the default config!

[21:53:54 ERROR]: Error occurred while enabling CommandItems v2.0.4 (Is it up to date?)
java.lang.RuntimeException: Failed to read config!
        at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:38) ~[?:?]
        at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.JsonMappingException: Enchantment level is either too low or too high (given 1, bounds are 0 to 0) (through reference chain: me.yamakaja.commanditems.data.CommandItemsConfig["items"]->java.util.LinkedHashMap["helpstick"]->me.yamakaja.commanditems.data.ItemDefinition["item"])
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1689) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:289) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890) ~[?:?]
        at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:36) ~[?:?]
        ... 12 more
Caused by: java.lang.IllegalArgumentException: Enchantment level is either too low or too high (given 1, bounds are 0 to 0)
        at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:438) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at me.yamakaja.commanditems.parser.ItemStackDeserializer.deserialize(ItemStackDeserializer.java:82) ~[?:?]
        at me.yamakaja.commanditems.parser.ItemStackDeserializer.deserialize(ItemStackDeserializer.java:22) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[?:?]
        at me.yamakaja.commanditems.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890) ~[?:?]
        at me.yamakaja.commanditems.parser.ConfigManager.parse(ConfigManager.java:36) ~[?:?]
        ... 12 more

**Comment by Yamakaja** [comment]
For future visitors: `Failed to read config!`
There is a syntax error in your config, and further down you'll see that `Enchantment level is either too low or too high (given 1, bounds are 0 to 0)`
