### ISSUE TITLE
console error on start

### ISSUE THREAD

**Issue by Goldenphelix** [Yamakaja/commanditems#6]
```
[Server] INFO [CommandItems] Enabling CommandItems v2.1.1
[Server] WARN [CommandItems] Could not save config.yml to plugins/CommandItems/config.yml because config.yml already exists.
[Server] ERROR Error occurred while enabling CommandItems v2.1.1 (Is it up to date?)
[Server] INFO java.lang.NullPointerException: null
[Server] INFO at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:79) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at me.yamakaja.commanditems.lib.co.aikar.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11) ~[?:?]
[Server] INFO at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingType$1.newTiming(TimingType.java:11) ~[?:?]
[Server] INFO at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:72) ~[?:?]
[Server] INFO at me.yamakaja.commanditems.lib.co.aikar.timings.lib.TimingManager.of(TimingManager.java:38) ~[?:?]
[Server] INFO at me.yamakaja.commanditems.lib.co.aikar.commands.BukkitCommandManager.<init>(BukkitCommandManager.java:96) ~[?:?]
[Server] INFO at me.yamakaja.commanditems.lib.co.aikar.commands.PaperCommandManager.<init>(PaperCommandManager.java:33) ~[?:?]
[Server] INFO at me.yamakaja.commanditems.CommandItems.onEnable(CommandItems.java:34) ~[?:?]
[Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-174]
[Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
[Server] INFO [CommandItems] Disabling CommandItems v2.1.1
```

**Comment by electronicboy** [comment]
https://github.com/Yamakaja/commanditems/blob/master/build.gradle#L52
This relocation is incorrect, relocating that will basically attempt to relocate timings itself which causes the timings library to fail, looks like we also have some issue with the fallback timings handler too...

**Comment by Yamakaja** [comment]
Fixed, thanks @electronicboy for the PR
